trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 8.x
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build and Publish API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    zipAfterPublish: true
    projects: '**/*.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish API'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactname: 'drop'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'Service connection Azure Resource Manager rg-v.verdouw'
    appType: 'webApp'
    appName: 'rademaker-plantool'
    deployToSlotOrASE: true
    resourceGroupName: 'rg-v.verdouw'
    slotName: 'production'
    package: '$(Build.ArtifactStagingDirectory)/drop/*.zip'
    deploymentMethod: 'zipDeploy'