// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using plantool.Data;

#nullable disable

namespace plantool.Migrations
{
    [DbContext(typeof(PlantoolDbContext))]
    [Migration("20250415072827_AddWorkCenter")]
    partial class AddWorkCenter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("plantool.Domain.Entities.ActivityType", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("OperationShortText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("plantool.Domain.Entities.CompetenceTeam", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Name");

                    b.ToTable("CompetenceTeams");
                });

            modelBuilder.Entity("plantool.Domain.Entities.Engineer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("CanDelegate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTeamName");

                    b.ToTable("Engineers");
                });

            modelBuilder.Entity("plantool.Domain.Entities.ProductTeam", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompetenceTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductLeadId")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Name");

                    b.HasIndex("CompetenceTeamName");

                    b.HasIndex("ProductLeadId");

                    b.ToTable("ProductTeams");
                });

            modelBuilder.Entity("plantool.Domain.Entities.Project", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectManager")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("plantool.Domain.Entities.ProjectActivity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan?>("AbsoluteWorkload")
                        .HasColumnType("time");

                    b.Property<string>("ActivityTypeCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("ActualFinishDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ActualStartDate")
                        .HasColumnType("date");

                    b.Property<string>("GeneralRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("LatestFinishDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LatestStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Network")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("OriginalFinishDate")
                        .HasColumnType("date");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TeamLeader")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TimeEstimated")
                        .HasColumnType("bigint");

                    b.Property<long?>("TimeSpent")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkBreakdownStructure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkCenter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("ActivityTypeCode");

                    b.HasIndex("ProjectId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("plantool.Domain.Entities.Engineer", b =>
                {
                    b.HasOne("plantool.Domain.Entities.ProductTeam", "ProductTeam")
                        .WithMany("Engineers")
                        .HasForeignKey("ProductTeamName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductTeam");
                });

            modelBuilder.Entity("plantool.Domain.Entities.ProductTeam", b =>
                {
                    b.HasOne("plantool.Domain.Entities.CompetenceTeam", "CompetenceTeam")
                        .WithMany("ProductTeams")
                        .HasForeignKey("CompetenceTeamName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("plantool.Domain.Entities.Engineer", "ProductLead")
                        .WithMany()
                        .HasForeignKey("ProductLeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompetenceTeam");

                    b.Navigation("ProductLead");
                });

            modelBuilder.Entity("plantool.Domain.Entities.ProjectActivity", b =>
                {
                    b.HasOne("plantool.Domain.Entities.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeCode");

                    b.HasOne("plantool.Domain.Entities.Project", "Project")
                        .WithMany("Activities")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("plantool.Domain.Entities.CompetenceTeam", b =>
                {
                    b.Navigation("ProductTeams");
                });

            modelBuilder.Entity("plantool.Domain.Entities.ProductTeam", b =>
                {
                    b.Navigation("Engineers");
                });

            modelBuilder.Entity("plantool.Domain.Entities.Project", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
